name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL (if want to use SSH keys, use git@github.com:XXXXX)'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'twrp-12.1'
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/mmtrt/android_device_xiaomi_evergreen'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
        default: 'twrp-12.1'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/xiaomi/evergreen'
      COMMON_TREE_URL:
        description: 'COMMON_TREE_URL (if no common tree, leave blank)'
        required: false
      COMMON_PATH:
        description: 'COMMON_PATH (if no common tree, leave blank)'
        required: false
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'evergreen'
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME'
        required: true
        default: 'twrp_evergreen'
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: true
        default: 'boot'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    # You can use either of the ubuntu-18.04 or ubuntu-20.04 runner
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"
 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v3

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt-mark hold python-is-python2 python2 snapd firefox
        sudo apt -y install gperf liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev  git device-tree-compiler lz4 xz-utils zlib1g-dev gcc g++ python3 python-is-python3 p7zip-full wget

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Get required deps
      run: |
        wget -q "https://github.com/mmtrt/Action-Recovery-builder/releases/download/3454574178/boot.img" -O twrp.img
        wget -q "https://github.com/mmtrt/Action-Recovery-builder/releases/download/3454575569/boot.img" -O pbrp.img
        wget -q "https://github.com/mmtrt/Action-Recovery-builder/releases/download/3454574872/boot.img" -O shrp.img
        wget -q "https://github.com/mmtrt/Action-Recovery-builder/releases/download/3454575570/boot.img" -O ofox.img
        wget -q "https://github.com/cfig/Android_boot_image_editor/releases/download/v13_preview3/boot_editor_v13_preview3.zip"
        7z x boot_editor_v13_preview3.zip
        mkdir workspace

    - name: Patch pbrp eea boot.img
      run: |
        cp pbrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_eea build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/pbrp-eea.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch shrp eea boot.img
      run: |
        cp shrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_eea build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/shrp-eea.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch twrp eea boot.img
      run: |
        cp twrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_eea build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/twrp-eea.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch ofox eea boot.img
      run: |
        cp ofox.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|ofoxfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_eea build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/ofox-eea.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch pbrp glo boot.img
      run: |
        cp pbrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_glo build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/pbrp-glo.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch shrp glo boot.img
      run: |
        cp shrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_glo build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/shrp-glo.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch twrp glo boot.img
      run: |
        cp twrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_glo build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/twrp-glo.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch ofox glo boot.img
      run: |
        cp ofox.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|ofoxfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_glo build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/ofox-glo.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch pbrp in boot.img
      run: |
        cp pbrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_in build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/pbrp-in.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch shrp in boot.img
      run: |
        cp shrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_in build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/shrp-in.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch twrp in boot.img
      run: |
        cp twrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_in build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/twrp-in.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch ofox in boot.img
      run: |
        cp ofox.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|ofoxfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_in build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/ofox-in.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch pbrp tur boot.img
      run: |
        cp pbrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_tur build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/pbrp-tur.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch shrp tur boot.img
      run: |
        cp shrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_tur build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/shrp-tur.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch twrp tur boot.img
      run: |
        cp twrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_tur build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/twrp-tur.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch ofox tur boot.img
      run: |
        cp ofox.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|ofoxfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_tur build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/ofox-tur.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch pbrp tw boot.img
      run: |
        cp pbrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_tw build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/pbrp-tw.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch shrp tw boot.img
      run: |
        cp shrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_tw build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/shrp-tw.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch twrp tw boot.img
      run: |
        cp twrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_tw build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/twrp-tw.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch ofox tw boot.img
      run: |
        cp ofox.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|ofoxfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_tw build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/ofox-tw.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch pbrp ru boot.img
      run: |
        cp pbrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_ru build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/pbrp-ru.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch shrp ru boot.img
      run: |
        cp shrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_ru build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/shrp-ru.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch twrp ru boot.img
      run: |
        cp twrp.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|twrpfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_ru build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/twrp-ru.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Patch ofox ru boot.img
      run: |
        cp ofox.img boot_editor_v13_preview3/boot.img
        cd boot_editor_v13_preview3 || exit ; chmod +x gradlew ;
        ./gradlew unpack ; cp build/unzip_boot/boot.json build/unzip_boot/b.json ; cat build/unzip_boot/b.json | sed -r 's|ofoxfastboot=1 ||;s/-[0-9]+\./12./;s/12.[0-9]+\./12.0./;s/12.0.[0-9]+/12.0.0/' &> build/unzip_boot/boot.json ; rm build/unzip_boot/b.json ; rm build/unzip_boot/kernel ; cp ../kernels/kernel_ru build/unzip_boot/kernel ; ./gradlew pack ; rm boot.img ; cp boot.img.signed ../workspace/ofox-ru.img ; rm -r build/unzip_boot ; rm boot.img.signed

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/*.img
        name: evergreen-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Version: MIUI V13.0.2.0 A12
          Region: EEA TUR TW RU

          Version: MIUI V13.0.3.0 A12
          Region: GLOBAL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
